schema_version = "1.1.0"

id = "lenticular"
version = "1.1.0"
name = "Lenticular"
tagline = "Combine multiple images into a lenticular print"
maintainer = "Wout Verswijveren <wwmverswijveren@proton.me>"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

# Optional metadata
website = "ko-fi.com/tonymurchison"
# tags = ["3D View", "Object"]
